GRPC_SERVER_PORT = ":8080"
IPERF_PORT = 3114
REST_PORT = 3113

HALT_ENDPOINT = 'halt'
TASK_ALLOCATION = 'allocate_task'
TASK_UPDATE = 'update_task'

CONTROLLER_DEFAULT_ROUTE = "/controller"
CONTROLLER_DEFAULT_PORT = 6502
CONTROLLER_REGISTER_DEVICE = "/register_device"
CONTROLLER_DAG_DISRUPTION = "/dag_disruption"
CONTROLLER_STATE_UPDATE = "/state_update"
