from enum import Enum

class EventTypes(Enum):
    OBJECT_DETECT_START = "OBJECT_DETECT_START"
    OBJECT_DETECT_FINISH = "OBJECT_DETECT_FINISH"
    LOW_COMP_START = "LOW_COMP_START"
    LOW_COMP_FINISH = "LOW_COMP_FINISH"
    EVENT_LOOP_FINISH = "EVENT_LOOP_FINISH"